### ISSUE TITLE
Update nuget feed with the latest version.

### ISSUE THREAD

**Issue by abeninskibede** [pusher/pusher-http-dotnet#24]
Hey guys I have latest version of pusher from nuget 2.1.1.1 which lacks some features like Cluster which is critical for me because I'm in europe.

![image](https://cloud.githubusercontent.com/assets/8179559/13641487/40bf5552-e621-11e5-886a-110df3a16d61.png)

Can you please push the latest version of your repo to Nuget.

**Comment by abeninskibede** [comment]
PusherServer.3.0.0-rc3 does not have cluster option either.

**Comment by hamchapman** [comment]
@abeninskibede 3.0.0-rc3 has the option to set the host, which you'll be able to use for now. If you want to connect to the eu cluster you'll want to specify the host as: `api-eu.pusher.com`

**Comment by abeninskibede** [comment]
```
            var options = new PusherOptions();
            options.HostName = "api-eu.pusher.com";

            return new Pusher(appId, appKey, appSecret, options);
```

This should work?

**Comment by abeninskibede** [comment]
Yeah it works.

**Comment by hamchapman** [comment]
Thank for confirming. We'll hopefully be officially releasing 3.0.0 in the near future so I'll close this for now.
