### ISSUE TITLE
ASP.net Core Support

### ISSUE THREAD

**Issue by yehiasalam** [pusher/pusher-http-dotnet#27]
Hi,

Will this work with asp.net core 1.x?

**Comment by ewmy** [comment]
Hi @yehiasalam, v4.0.0 of the library, which we've just released, supports .NET Core.

It's available on NuGet as an RC: https://www.nuget.org/packages/PusherServer/4.0.0-rc1

It would be great if you could try it out and give us some feedback 😄

**Comment by yehiasalam** [comment]
great thanks will check it out
