### ISSUE TITLE
Could not load file or assembly 'RestSharp, Version=105.0.1.0

### ISSUE THREAD

**Issue by iw-cnickeson** [pusher/pusher-http-dotnet#36]
I am running into this issue since I have other dependencies that use RestSharp and is using the latest version. Is there a way I can get around pusher using an older version of RestSharp?

**Comment by ewmy** [comment]
Hi,

Good news - we've just deployed v4.1.0 of the library to NuGet, which no longer has a dependency on RestSharp.

I'll close this issue now, but if you have any other problems let us know.

Sam

**Comment by iw-cnickeson** [comment]
Hey Sam,

Thanks for the update!

Cheers

Colin Nickeson
Software Developer
Innovative Way, Inc.
colin.nickeson@innovativewayinc.com | 563-219-0026
