### ISSUE TITLE
TriggerAsync returning void?

### ISSUE THREAD

**Issue by jcd79** [pusher/pusher-http-dotnet#37]
Hi!

I don't really get this. All you examples and source code show pusher.TriggerAsync returning Task<ITriggerResult>. But when I use the code from C# (PuserServer version 3.0.0) it shows all versions of the method returning void and a different method profile than shown in your docs. "Simplest" profile with TriggerAsync(channel, event, data) is also not available.
Normal Trigger works as expected. This all seems very strange to me, but I cannot find any explanation in my setup.

Any idea? Thanks.
/Jacob

![image](https://cloud.githubusercontent.com/assets/10612840/24580100/a7d87f44-1702-11e7-9a1c-2078b0b05723.png)

![image](https://cloud.githubusercontent.com/assets/10612840/24580122/01741c8e-1703-11e7-806a-468e1229afb0.png)

![image](https://cloud.githubusercontent.com/assets/10612840/24580185/1387168c-1704-11e7-9557-dc647b508a93.png)

**Comment by imaji** [comment]
Hi Jacob,

The current front page version on GitHub is the 4.0.0 Release Candidate.  You can download it from nuget here https://www.nuget.org/packages/PusherServer/4.0.0-rc1  I'd recommend giving it a go.

If you want to see the docs and examples for 3.0.0 checkout the tagged release for 3.0.0 here https://github.com/pusher/pusher-http-dotnet/tree/3.0.0

Best regards,
John

**Comment by jcd79** [comment]
Aah, my bad. Thanks.

**Comment by imaji** [comment]
Not at all, happy to help :)
