### ISSUE TITLE
The response body from the Pusher HTTP endpoint could not be parsed as JSON

### ISSUE THREAD

**Issue by lukpep** [pusher/pusher-http-dotnet#42]
```
_pusher = new Pusher(settings.AppId, settings.Key, settings.Key, new PusherOptions {Encrypted = true});
var triggerResult = await _pusher.TriggerAsync(channelName, @event, eventParams);
```

gives me exception:

> The response body from the Pusher HTTP endpoint could not be parsed as JSON: System.Net.Http.StreamContent

StackTrace:

> Exception PusherServer.Exceptions.TriggerResponseException was thrown: The response body from the Pusher HTTP endpoint could not be parsed as JSON:
> System.Net.Http.StreamContent in PusherServer.Core	at PusherServer.TriggerResult..ctor(HttpResponseMessage response, String responseContent)
>    at PusherServer.RestfulClient.PusherRestClient.<ExecutePostAsync>d__8.MoveNext()

Any ideas? I'm using Net Core 1.1.2 and PusherServer 4.1.0

**Comment by lukpep** [comment]
`_pusher = new Pusher(settings.AppId, settings.Key, settings.Key, new PusherOptions {Encrypted = true});`
doubled settings.Key - should be settings.Secret although error message should be more descriptive

**Comment by dn32** [comment]
> ```
> _pusher = new Pusher(settings.AppId, settings.Key, settings.Key, new PusherOptions {Encrypted = true});
> var triggerResult = await _pusher.TriggerAsync(channelName, @event, eventParams);
> ```
> 
> gives me exception:
> 
> > The response body from the Pusher HTTP endpoint could not be parsed as JSON: System.Net.Http.StreamContent
> 
> StackTrace:
> 
> > Exception PusherServer.Exceptions.TriggerResponseException was thrown: The response body from the Pusher HTTP endpoint could not be parsed as JSON:
> > System.Net.Http.StreamContent in PusherServer.Core	at PusherServer.TriggerResult..ctor(HttpResponseMessage response, String responseContent)
> > at PusherServer.RestfulClient.PusherRestClient.d__8.MoveNext()
> 
> Any ideas? I'm using Net Core 1.1.2 and PusherServer 4.1.0

The problem may occur if your computer time is wrong

**Comment by max-favilli** [comment]
You get that error when the message is >10k as well.
