### ISSUE TITLE
Pusher: TriggerResponseException

### ISSUE THREAD

**Issue by fred5577** [pusher/pusher-http-dotnet#45]
Hey

I am trying to setup pusher. I've create an account, set in the different keys, and triple checked that they are correct. But everytime I try to triggerasync i throws.

PusherServer.Exceptions.TriggerResponseException: The response body from the Pusher HTTP endpoint could not be parsed as JSON

Get any ideas why? 
There is no problem with subscribing to the channel in my react code, and I can send events from the debug console on my account.

        [HttpPost("select")]
        public async Task<ActionResult> Select([FromForm] SelectBooth booth ) {
            var options = new PusherOptions {
                Cluster = "eu",
                Encrypted = true
            };

            var pusher = new Pusher(
              "515429",
              "c1f5fd106f027f2ae68a",
              "910b583663118349df9e");

            var result = await pusher.TriggerAsync(
              "3e105489-9dba-4d9b-9dba-40c49437935b",
              "booth-seleceted",
              new { message = "hello world" });

            return NoContent();
        }

**Comment by imaji** [comment]
Hi,

I'll have a look later on this afternoon and see if I can reproduce the problem.  Have you managed to capture the response?

Thanks,
John

**Comment by fred5577** [comment]
Hej

I now tried creating a new project, and copied the same code in as in the example I gave above and it works. It sends the message. 

Do anybody have any idea what could be blocking pusher.Triggerasync in the project I am working on?

**Comment by fred5577** [comment]
I figured out the problem. I am running my aspnetcore on a docker container. The problem was that the docker container did not synchronize the time, so it was a couple of days behind. So the difference in time seems to have caused the problem.
