### ISSUE TITLE
Support .NET Standard

### ISSUE THREAD

**Issue by andrewlock** [pusher/pusher-http-dotnet#47]
Hi, I'm using your library in an app that I'm porting to .NET Core, and would be really useful if it supported .NET Standard 2.0 as well as .NET Framework?

Is that something you'd be happy with?  If so, I can send a PR for the changes?

**Comment by Misiu** [comment]
any updates?

**Comment by Misiu** [comment]
ping

**Comment by kn100** [comment]
Hey! 

Really sorry for the slow reply here! The library currently targets NET Standard 1.6 - and there is nothing in flight right now to bring 2.0 compatibility. What benefit do you get from it targeting 2.0? I will mention this in our next standup as something that you've asked for.

W.r.t the PR, if you feel up for it, I'd be more than happy to review and potentially merge, but that's totally up to you!

**Comment by andrewlock** [comment]
Hey, the code in this repo and [the current NuGet package doesn't appear to target .NET Standard at all](https://www.nuget.org/packages/PusherServer/) - it looks like it's [targeting `net45`](https://github.com/pusher/pusher-http-dotnet/blob/master/PusherServer/PusherServer.csproj#L13) as far as I can see!

Regarding 2.0 vs 1.6 - there's actually a number of reasons for this [(as described in this doc)](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting):

*  .NET Standard 1.5 and 1.6 are essentially deprecated, because they can cause potential issues with .NET Framework 4.6.1 (which claims to support 2.0, but doesn't quite, and is missing APIs that are in 1.5. and 1.6)
* Referencing a library that supports .NET Standard 1.6 can result in a large NuGet dependency tree due to the dependencies in [NetStandard.Library](https://www.nuget.org/packages/NETStandard.Library/). Official guidance is to avoid adding a 1.x target unless you want the widest support
* If you do add a 1.x target, you should add a 2.0 target

There's also some issues with the compat shim in .NET Framework 4.6.1 so for maximum compatibility, an example of the best combination of targets is:

```
<TargetFramework>netstandard1.0;netstandard2.0;net461;net472</TargetFramework>
```

Converting to .NET Standard will also involve converting to the .NET SDK for .csproj files which will take a bit of work, but I'll see if I can get round to it soon

**Comment by kn100** [comment]
I will raise this with tomorrow in our standup and let you know the outcome. Thanks for informing!

**Comment by kn100** [comment]
I will raise this tomorrow in out standup and let you know the outcome!

**Comment by andrewlock** [comment]
Hey, just wondered how this went down at your standup? 🙂

**Comment by Misiu** [comment]
@kn100 aby updates?

**Comment by Misiu** [comment]
@kn100 any updates?

**Comment by andrewlock** [comment]
Hi @kn100,

I was just looking at this again, I'm a bit confused by your code setup in the library 🤔  The PusherServer "project" is made very complicated by the fact it's building separately, and "manually" packaging the Nuget using the nuspec. The new SDK-style csproj (which you've used for the PusherServer.Core project) could handle all this for you...

An additional problem is that while you're building and packaging a.NET Standard 1.6 version of the library in the NuGet, I'm not sure it's actually registering properly, as nuget.org doesn't list the supported versions (Compare to [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) for example.

Would you be open to a PR that simplifies all this for you? I'll try and put something together tonight if so.

**Comment by Misiu** [comment]
@damdo any updates? Could You look at @andrewlock PR?

**Comment by djvickx** [comment]
Any update on this? We are still unable to use pusher server in .net standard library version 2.0. Does any one found a workaround to use pusher server in .net standard 2.0?

**Comment by damdo** [comment]
Hey @Misiu, @djvickx and @andrewlock,
thank you for reaching out. It is within our plans to have support in the library for .NET Standard 2.0.  @andrewlock did a great job on that and it is in out plans to have it, reviewed and merged fairly soon.
Thank you for bearing with us.

**Comment by Misiu** [comment]
@damdo really looking to see it in the near future :)
I want to use .NET Core 3.1 on the backend so .NET Standard 2.1 would be even better :)
Unfortunately, I need .NET 4.0 on the client, but there is separate repo for it and I''m working on adding support (will create PR when finished)

@damdo when do You plan to release the next version? I need an ETA to plan my project.

**Comment by djvickx** [comment]
For anyone who wants to use it pusher in .net standard library, I have found out a way that you can set multiple target frameworks in your .net standard library .csproj file e.g you can use netcore20 or net461 depending on the .net core or .net framework in which you want to include .net standard library. 
This solved my issue and I am able to use pusher with .net standard 2.0 :)

**Comment by elverkilde** [comment]
Sorry for the delay on this, @andrewlock 's PR is now incorporated along with a number of other improvements. Please give the latest release a try and let us know if this resolves the issue.

I am closing this for now, but feel free to re-open if you are still having problems.
