### ISSUE TITLE
App key "Key"not in this cluster. Did you forget to specify the cluster?

### ISSUE THREAD

**Issue by Ruben170** [pusher/pusher-http-dotnet#50]
I keep getting this error even thought this is the correct app key. I have tried multiple clusters but none seem to work also made multiple new projects.

my Controller
`private Pusher pusher;
        //class constructor
        public ChatController()
        {
            var options = new PusherOptions();
            options.Cluster = "us2";

            pusher = new Pusher(
                "757549",
                "de7472cb799f79debc6e",
                "f14740af33b9ee255162",
                options
            );
        }`

my javascript
`//Pusher client side setup
        var pusher = new Pusher('757549',
            {
                cluster: 'us2'
            }); 
        pusher.connection.bind('connected',
            function() {
                socketId = pusher.connection.socket_id;
            });`

**Comment by kn100** [comment]
That options object, did you specify the cluster in there too?

**Comment by kn100** [comment]
That options object, did you specify the cluster in there too?
