### ISSUE TITLE
Add option for configurable argument for timeout

### ISSUE THREAD

**Issue by ccaseypusher** [pusher/pusher-http-dotnet#61]
Currently the the timeout for PusherRestClient is determined by the default timeout in the dotnet http client library:

This is currently set at 100 seconds:

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=netcore-3.1

This is an extremely long timeout and it would be helpful to be able to override this. It should be possible by adding an optional argument for PusherRestClient - https://github.com/pusher/pusher-http-dotnet/blob/3e9e1deb4206433835e5852713c5484e9a97204c/PusherServer.Core/RestfulClient/PusherRestClient.cs#L35

**Comment by marknadig** [comment]
@elverkilde 30s is better than 100, and definitely a better default. However, it is still not configurable as requested by this bug. IMHO there's not good reason to fix this value vs support option.

**Comment by stuarthunter** [comment]
Completely agree with @marknadig that this is essential.  We had to create a new PusherRestClient implementation just to expose the Timeout property on the underlying HttpClient instance.  We can then instantiate Pusher as follows:

```
_pusher = new PusherServer.Pusher(...)
{
    RestClient = new PusherRestClientEx(...)
    {
        Timeout = TimeSpan.FromSeconds(5)
    },
    ...
});
```
