### ISSUE TITLE
Application never gets connected to Pusher

### ISSUE THREAD

**Issue by grijalvadylan** [pusher/pusher-http-dotnet#62]
I followed all steps to connect to Pusher but the application nevers get connected, i really did everything but never gets connected, help!:(

**Comment by elverkilde** [comment]
hi @grijalvadylan, can you give us a bit more detail? What is the error you are getting? Which cluster are you using?

**Comment by elverkilde** [comment]
I'm closing this, as it seems to be stale. Feel free to re-open with more details!
