### ISSUE TITLE
Using PursherClient library in .Net Framework 4.7 gets an error in TriggerAsync

### ISSUE THREAD

**Issue by sergiohj** [pusher/pusher-http-dotnet#67]
Hello,

I need to use PusherServer library in a .Net Framework 4.7 application but when I use the method TriggerAsync I get the next error:

Could not load file or assembly 'PusherServer.Core, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

It seems that the library is not working for this .Net Framework version. What can i do to send a notifications from this app type?

Regards.

**Comment by erwin42** [comment]
Reference PusherServer.dll and not PusherServer.Core.dll

**Comment by elverkilde** [comment]
Hi @sergiohj, as @erwin42 mentions, you should use PusherServer instead. We recently removed the Core artefact entirely, so hopefully that clears up this confusion.

I will close this issue, but feel free to re-open if you are still having issues.
