### ISSUE TITLE
What should be the scope of Pusher instance

### ISSUE THREAD

**Issue by TailyFair** [pusher/pusher-http-dotnet#82]
Hi,

Our API should send Pusher notifications in certain endpoints.
Should we create new `Pusher` for each HTTP request or should we create `Pusher` singleton and reuse it every time?

Basically what `Pusher` scope should be used - `Singleton`, `Scoped` or `Transient`?

Thanks!

**Comment by amad** [comment]
@TailyFair You can create one instance and reuse it.

This server library makes request to Pusher HTTP API and doesn't hold a lot of resources. So there is little to no overhead to create multiple instances, but it's a better practice to use single instance.

**Comment by amad** [comment]
I'll close this issue for now. Please let me know if you have more questions and feel free to open a new issue when needed.
