### ISSUE TITLE
Need clearer documentation on the recommended lifetime of Pusher, PusherOptions

### ISSUE THREAD

**Issue by burns47** [pusher/pusher-http-dotnet#83]
If I'm reading the code correctly it appears that a new instance of `HttpClient` is created every time a `PusherOptions` is created.  According to Microsoft (https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/) this technique can lead to socket exhaustion:

> These classes are intended to be instantiated once and reused throughout the lifetime of an application. However, it's a common misunderstanding that these classes should be acquired only as necessary and released quickly. (The ones listed here happen to be .NET libraries, but the pattern is not unique to .NET.) The following ASP.NET example creates an instance of HttpClient to communicate with a remote service. You can find the complete sample here.
> 
> ...
> 
> **In a web application, this technique is not scalable. A new HttpClient object is created for each user request.** Under heavy load, the web server may exhaust the number of available sockets, resulting in SocketException errors.

The docs should say that Pusher (or at least PusherOptions) is intended to be a singleton in order to prevent socket leaks.

**Comment by benjamin-tang-pusher** [comment]
Thanks for this. Since people occasionally ask about this, I've added this to the readme. #85
