### ISSUE TITLE
InvalidOperationException "You cannot trigger to multiple channels when using encrypted channels."

### ISSUE THREAD

**Issue by m3taphysics** [pusher/pusher-http-dotnet#87]
I am implementing channel encryption within a project:

`    public async Task<ITriggerResult> TriggerAsync(
      string[] channelNames,
      string eventName,
      object data,
      ITriggerOptions options = null)`

We use ability to trigger across multiple channels in quite a few places. I have now changed this to use TriggerAsync with a single channel name, but this just feels like a work around.

Can anybody confirm if this is safe to do, and is there a specific reason why you cannot trigger on multiple channels when using encryption? Is this just a current limitation of the library. Or a limitation of pusher.

Many thanks

**Comment by benw-pusher** [comment]
At this time we don't support triggering to multiple encrypted channels in a single request, the approach you are currently using is the supported approach. I will pass this feedback on to the product team for consideration in the future release, however this is unlikely to be something we address in the short term.
