### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by NareshBanala-dev** [pusher/pusher-http-dotnet#94]
I have "PRO" plan, leveraging 5.0.0 version. I am seeing below error 5.0.0.

"An attempt was made to access a socket in a way forbidden by its access permissions. ([api-mt1.pusher.com:443](http://api-mt1.pusher.com:443/))"

![image](https://github.com/pusher/pusher-http-dotnet/assets/79455103/0351fd07-57a5-44d7-9664-85c7c29cabdd)

**Comment by benw-pusher** [comment]
This error is encountered when a firewall or similar service blocks the request - Windows Firewall or Azure service limits can cause this error.
